stlevkov/budgeta

- mybudget.app/src/main/java/com/mybudget/app/Application.java
- mybudget.app/src/main/java/com/mybudget/app/controller/IncomeController.java
- mybudget.app/src/main/java/com/mybudget/app/model/Expense.java
- mybudget.app/src/main/java/com/mybudget/app/model/Income.java
- mybudget.app/src/main/java/com/mybudget/app/model/Saving.java
- mybudget.app/src/main/java/com/mybudget/app/model/TransactionType.java
- mybudget.app/src/main/java/com/mybudget/app/repository/IncomeRepository.java
- mybudget.app/src/main/java/com/mybudget/app/service/IncomeService.java
- mybudget.app/src/main/java/com/mybudget/app/service/IncomeServiceImpl.java
- mybudget.app/src/test/java/com/mybudget/app/ApplicationTests.java
Added CORS exception;
Disabled Test class;
> [BUD-1] Added Income implementation;

- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/pages/components/NavBar.js
The value is sent after pressing enter;
> [#25] Added Input Target Saving field;

- frontend/src/components/dialogs/IncomesDialog.js
- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/TargetSaving.js
- mybudget.app/src/main/java/com/mybudget/app/controller/CostAnalyticController.java
Added IconButton for new incomes only mock for now;
> [#29] Added INCOMES sum and SeeDetails dialog with tabs for two incomes;

- frontend/src/App.js
- frontend/src/components/SettingsButton.js
- frontend/src/components/ThemeSwitch.js
- frontend/src/components/dynamic/ExpensesStack.js
- frontend/src/components/dynamic/SavingsStack.js
- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/components/dynamic/Title.js
- frontend/src/pages/home/Dashboard.js
Moved theme creation from Dashboard.js to App.js
Fixed theme switch
Removed some unused logs
Fixed keys errors on Lists
> Fixed issue #18

- frontend/src/components/SettingsButton.js
- frontend/src/components/dialogs/CreateSavingDialog.js
- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/pages/components/NavBar.js
- frontend/src/pages/components/Sidebar.js
- frontend/src/pages/components/SidebarLinkList.js
> Added create buttons

- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/ExpensesStack.js
- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/pages/components/NavBar.js
- frontend/src/pages/home/Dashboard.js
Dynamic render daily recommended field;
> [#45] Fixed target saving button layout;

- frontend/src/components/dialogs/CreateSavingDialog.js
- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/ExpensesStack.js
- frontend/src/components/dynamic/SavingsStack.js
Removed useEffect dependencies causing infinity loops;
> [#52] Added remove Saving functionality;

- frontend/src/components/dialogs/CreateExpenseDialog.js
- frontend/src/components/dialogs/CreateSavingDialog.js
- frontend/src/components/dynamic/ExpensesStack.js
- frontend/src/components/dynamic/SavingsStack.js
- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/pages/components/NavBar.js
- frontend/src/pages/components/SidebarLinkList.js
Moved saving icon;
Fixed colors;
> [#55] Fixed New Saving to re-render savingsStack;

- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/ExpensesStack.js
- frontend/src/components/dynamic/SavingsStack.js
- frontend/src/components/dynamic/TargetSaving.js
- frontend/src/components/dynamic/TargetStack.js
- frontend/src/pages/home/Dashboard.js
- frontend/src/resources/data.json
- mybudget.app/src/main/java/com/mybudget/app/controller/CostAnalyticController.java
- mybudget.app/src/main/java/com/mybudget/app/controller/ExpenseController.java
- mybudget.app/src/main/java/com/mybudget/app/controller/IncomeController.java
- mybudget.app/src/main/java/com/mybudget/app/controller/SavingController.java
Fixed Expenses and Saving edit fields;
> [#65] Added data.json for demo data;

- frontend/src/components/dialogs/CreateSavingDialog.js
- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/SavingsStack.js
- frontend/src/pages/home/Dashboard.js
Affects only New Savings for now;
> Added Snackbar for Error messages;

- frontend/src/components/dialogs/WithdrawSavingsDialog.js
- frontend/src/components/dynamic/CostAnalyticStack.js
- frontend/src/components/dynamic/TargetStack.js
- frontend/src/components/dynamic/Unexpected.js
- frontend/src/pages/home/Dashboard.js
Improved also some tooltips;
Free Slot card replaced with Account Summary info; Created mock ChangeAccountAmount dialog;
> Improved Target Savings, analytic stack;

- frontend/src/App.js
- frontend/src/pages/components/NavBar.js
- frontend/src/pages/components/Sidebar.js
- frontend/src/pages/home/Dashboard.js
- fixed some sizes
- changes on template elements
> Fixes on the template

- frontend/src/layouts/Dashboard.jsx
- using material-react-toastify for notification -removed unused imports
-mui auto-updated dependencies in package-lock.json
> Fixed issue #83

- frontend/src/components/dialogs/CreateExpenseDialog.jsx
- frontend/src/components/dialogs/CreateSavingDialog.jsx
- frontend/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- frontend/src/components/stacks/SavingsStack/SavingsStack.jsx
- fixed missing edited files from issue #83
> Fixed issue #88

- frontend/src/components/stacks/MonitoringStack/TargetSavingChart.jsx
> Not a bug, animation triggers multiple times;

- frontend/src/components/dialogs/CreateIncomeDialog.jsx
- frontend/src/components/dialogs/CreateSavingDialog.jsx
- frontend/src/components/dialogs/ViewIncomesDialog.jsx
- frontend/src/components/stacks/SavingsStack/SavingsStack.jsx
> OnClick must be places on the Button, not the icon

- frontend/src/components/dialogs/CreateExpenseDialog.jsx
- frontend/src/components/dialogs/CreateSavingDialog.jsx
- frontend/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- frontend/src/components/stacks/SavingsStack/SavingsStack.jsx
- additionally moved the "add" methods in dialogs
> Fixed issue #106

- frontend/src/components/dialogs/ViewIncomesDialog.jsx
- frontend/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- frontend/src/layouts/Dashboard.jsx
#126 Fix uncontrolled controlled by not setting to undefiend; 
#127 Fix p descendant warning by adding component={'div'} to typography;
> #121 Fix key warning by adding key={index} to tabpanel;

- frontend/src/api/RestClient.jsx
- frontend/src/components/dialogs/CreateExpenseDialog.jsx
- frontend/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- frontend/src/contexts/ExpensesState.jsx
- fixed updating of all expenses on CRUD events
- fixed event callbacks to use the restClient implementation
- added delete methods to restClient
> Fixed issue #139

- frontend/src/components/dialogs/CreateSavingDialog.jsx
- frontend/src/components/stacks/SavingsStack/SavingsStack.jsx
- frontend/src/contexts/UnexpectedState.jsx
- frontend/src/resources/config.json
- temporary fix on unexpectedEndpoint( will be fixed in future commit)
- fixed updating of sum all unexpected on CRUD events
- fixed event callbacks to use the restClient implementation
> Fixed issue #140

- frontend/src/api/RestClient.jsx
- frontend/src/components/dialogs/CreateBalanceTransactionDialog.jsx
- frontend/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- frontend/src/contexts/BalanceAccountState.jsx
- frontend/src/contexts/CostAnalyticState.jsx
- frontend/src/resources/config.json
- frontend/src/utils/AppUtil.jsx
- mybudget.app/src/main/java/com/mybudget/app/controller/BalanceController.java
- mybudget.app/src/main/java/com/mybudget/app/controller/CostAnalyticController.java
- mybudget.app/src/main/java/com/mybudget/app/model/BalanceTransaction.java
- mybudget.app/src/main/java/com/mybudget/app/model/CostAnalytic.java
- mybudget.app/src/main/java/com/mybudget/app/repository/BalanceRepository.java
- mybudget.app/src/main/java/com/mybudget/app/service/BalanceService.java
- mybudget.app/src/main/java/com/mybudget/app/service/BalanceServiceImpl.java
- mybudget.app/src/main/java/com/mybudget/app/service/CostAnalyticServiceImpl.java
- mybudget.app/src/main/java/com/mybudget/app/service/SavingServiceImpl.java
BalanceTransactions yet to be included when they are need, but the implementation is ready;
> #86 Implemented Account Balance;

- frontend/src/components/dialogs/CreateIncomeDialog.jsx
- frontend/src/components/dialogs/ViewIncomesDialog.jsx
- frontend/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- frontend/src/contexts/IncomesState.jsx
- changed dialogs to use income state and rest methods
- fixed sum value to automatically update in CostAnalyticStack on state change in dialogs
> Refactored Incomes using context and restClient

- frontend/src/api/RestClient.jsx
- frontend/src/components/dialogs/CreateExpenseDialog.jsx
- frontend/src/components/dialogs/CreateIncomeDialog.jsx
- frontend/src/components/dialogs/CreateSavingDialog.jsx
- frontend/src/components/dialogs/ViewIncomesDialog.jsx
- frontend/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- frontend/src/components/stacks/SavingsStack/SavingsStack.jsx
- frontend/src/contexts/BalanceAccountState.jsx
- frontend/src/contexts/CostAnalyticState.jsx
- frontend/src/contexts/ExpensesState.jsx
- frontend/src/contexts/IncomesState.jsx
- frontend/src/contexts/UnexpectedState.jsx
> [#163] Refactored RestClient

- README.md
- setup/autorun.sh
- setup/build.sh
- setup/express_server/package-lock.json
- setup/install.sh
- setup/spring.sh
- setup/systemd/budgeta-sdk.service
- setup/systemd/budgeta-ui.service
- setup/systemd/env.sh
- setup/systemd/start_sdk.sh
- setup/systemd/start_ui.sh
- ui/package-lock.json
> Replace pm2 with systemd

- .gitignore
- ui/package-lock.json
- ui/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- ui/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- ui/src/components/stacks/SavingsStack/SavingsStack.jsx
- ui/src/index.css
- ui/src/layouts/Dashboard.jsx
- ui/src/layouts/SideBar.jsx
Fixing Circular progress of Expenses and Unexpected to show real percentage;
Added descending sorting for Expenses and Unexpected; 
Fixed Sidebar not stretching to the bottom;
fixing gitignore;
> Minor change to the design, added sorting, fixing sidebar height, fixed circluar progress

- sdk-api/src/main/java/com/budgeta/sdk/api/AccountBalanceScheduler.java
- sdk-api/src/main/java/com/budgeta/sdk/api/model/BalanceTransaction.java
- sdk-api/src/main/java/com/budgeta/sdk/api/model/Dashboard.java
- sdk-api/src/main/java/com/budgeta/sdk/api/repository/CostAnalyticRepository.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/CostAnalyticService.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/CostAnalyticServiceImpl.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/DashboardService.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/DashboardServiceImpl.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/ExpenseService.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/ExpenseServiceImpl.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/IncomeService.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/IncomeServiceImpl.java
- sdk-api/src/main/java/com/budgeta/sdk/api/utils/ArithmeticUtil.java
- ui/src/components/dialogs/CreateBalanceTransactionDialog.jsx
The Scheduler will be activated automatically at the end of each month at midnight;
> Implemented Balance Account Scheduler

- ui/src/api/RestClient.ts
- ui/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- ui/src/contexts/ExpensesState.ts
- ui/src/contexts/IncomesState.ts
- ui/src/contexts/UnexpectedState.ts
- ui/src/utils/RestUtil.jsx
Adding created object to the callback function;
> Fixed Income, Expense, Unexpected cannot be deleted when just created;

- sdk-api/src/main/java/com/budgeta/sdk/api/model/Expense.java
- sdk-api/src/main/java/com/budgeta/sdk/api/service/ExpenseServiceImpl.java
- ui/src/components/dialogs/ViewExpensesDialog.jsx
- ui/src/components/dialogs/ViewIncomesDialog.jsx
- ui/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- ui/src/components/stacks/ExpensesStack/ExpensesStack.jsx
Added view expense dialog only as a frontend component; Fixed the date formatting in the view Income dialog;
> Added loan type and progress bar to the frontend component;

- sdk-api/pom.xml
Accessible on /actuator/health
> Adding Health actuator

- README.md
- setup/express_server/server.js
Changed port for Azure Deployments on Web Service NODE Container
> Provided option to use both PORT and BUDGETA_UI_PORT in express

- README.md
- ui/src/contexts/SettingState.ts
- ui/src/resources/config.js
fixed typo in dashboard endpoint
> Configuration for http-https protocol added for the react ui

- ui/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- ui/src/components/stacks/UnexpectedsStack/UnexpectedsStack.jsx
- ui/src/contexts/CostAnalyticState.ts
- ui/src/contexts/UnexpectedState.ts
- ui/src/layouts/Dashboard.jsx
Implemented Summ All Expenses  to be calculated upon Expenses or Unexpected change in CostAnalytic stack card
> Added sum of Expenses and Unexpected in All Expenses card

- ui/package-lock.json
- ui/src/components/stacks/CostAnalyticStack/CostAnalyticStack.jsx
- ui/src/components/stacks/ExpensesStack/ExpensesStack.jsx
- ui/src/components/stacks/MonitoringStack/StatisticChart.jsx
- ui/src/components/stacks/MonitoringStack/UsagesPieChart.jsx
- ui/src/components/stacks/NavigationStack/SettingsButton.jsx
- ui/src/components/stacks/UnexpectedsStack/UnexpectedsStack.jsx
- ui/src/contexts/DashboardState.ts
- ui/src/contexts/ExpensesState.ts
- ui/src/layouts/Dashboard.jsx
- ui/src/utils/Util.ts
fixed redundant calls for aggregation data on app loading
> Adding skeleton loading

- setup/express_server/package.json
- setup/express_server/server.js
Migrated express server file to ES6;
> Changed express routing to find files based on abs path;

- sdk-api/src/main/java/com/budgeta/sdk/api/config/SecurityConfig.java
WithCredentials true sent from frontend
> Enabling Spring to allow credentials

- sdk-api/src/main/java/com/budgeta/sdk/api/config/SecurityConfig.java
- sdk-api/src/main/java/com/budgeta/sdk/api/logging/LoggingFilter.java
revert the change in allow credentials
> Adding more logs when redirecting
